# Python Programming Basic Assignment - 8

### Question 1. 
##### Write a Python Program to Add Two Matrices?

#### Answer: 


In [1]:
import numpy as np

matrix1 = np.array([[1,2,3],
        [4,5,6],
        [7,8,9]])
matrix2 = np.array([[9,8,7],
        [6,5,4],
        [3,2,1]])

matrix_sum = np.add(matrix1,matrix2)
print("The Sum of the matrices \n\n{}  and \n\n{}  is \n\n{} ".format(matrix1,matrix2,matrix_sum))

The Sum of the matrices 

[[1 2 3]
 [4 5 6]
 [7 8 9]]  and 

[[9 8 7]
 [6 5 4]
 [3 2 1]]  is 

[[10 10 10]
 [10 10 10]
 [10 10 10]] 


### Question 2. 
##### Write a Python Program to Multiply Two Matrices?

#### Answer:


In [2]:
import numpy as np

matrix1 = np.array([[1,2,3],
        [4,5,6],
        [7,8,9]])
matrix2 = np.array([[9,8,7],
        [6,5,4],
        [3,2,1]])

matrix_product = np.dot(matrix1,matrix2)
print("The Product of the matrices \n\n{}  and \n\n{}  is \n\n{} ".format(matrix1,matrix2,matrix_product))

The Product of the matrices 

[[1 2 3]
 [4 5 6]
 [7 8 9]]  and 

[[9 8 7]
 [6 5 4]
 [3 2 1]]  is 

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]] 


### Question 3. 
##### Write a Python Program to Transpose a Matrix?

#### Answer:


In [3]:
import numpy as np

matrix1 = np.array([[1,2,3],
        [4,5,6],
        [7,8,9]])


matrix_transpose = np.transpose(matrix1)
print("The Transpose of the matrix \n\n{} is \n\n{} ".format(matrix1,matrix_transpose))

The Transpose of the matrix 

[[1 2 3]
 [4 5 6]
 [7 8 9]] is 

[[1 4 7]
 [2 5 8]
 [3 6 9]] 


### Question 4. 
##### Write a Python Program to Sort Words in Alphabetic Order?

#### Answer:


In [4]:
def words_sorter():
    
    user_input = input("Enter a string of words to sort them in alphabetical order: ")
    print()
    sorted_list = sorted(user_input.lower().split())
    print(' '.join(sorted_list))

words_sorter()

Enter a string of words to sort them in alphabetical order:  Write a Python Program to Sort Words in Alphabetic Order

a alphabetic in order program python sort to words write


### Question 5. 
##### Write a Python Program to Remove Punctuation From a String?

#### Answer:


In [5]:
def punctuation_remover():
    import string
    user_input = input("Enter the string from which you want to remove the punctuation: ")
    output = ''.join([i for i in user_input if i not in string.punctuation])
    return output

punctuation_remover()

Enter the string from which you want to remove the punctuation: Write a Python Program to Remove Punctuation From a String?~!@#$%^&*()_+|


'Write a Python Program to Remove Punctuation From a String'